sudo: required
services:
  - docker

before_install:
  - docker build -t kishlin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kishlin/react-test npm test -- --coverage

after_success:
  - docker build -t kishlin/multi-nginx ./nginx
  - docker build -t kishlin/multi-client ./client
  - docker build -t kishlin/multi-server ./server
  - docker build -t kishlin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
  # Take thso images and push them to docker hub
  - docker push kishlin/multi-nginx
  - docker push kishlin/multi-client
  - docker push kishlin/multi-server
  - docker push kishlin/multi-worker